DB_SESSION = "DB_SESSION"
SETTINGS = "SETTINGS"

# services
TOKEN_WALLET_SERVICE = "TOKEN_WALLET_SERVICE"
TRANSACTION_SERVICE = "TRANSACTION_SERVICE"
TOKEN_PACKAGE_SERVICE = "TOKEN_PACKAGE_SERVICE"
TOKEN_RATE_SERVICE = "TOKEN_RATE_SERVICE"
REFILL_PRODUCT_SERVICE = "REFILL_PRODUCT_SERVICE"
TIPS_PRODUCT_SERVICE = "TIPS_PRODUCT_SERVICE"
PAYMENT_SAGA = "PAYMENT_SAGA"
WEB_CLIENT = "WEB_CLIENT"

# facades
REFILL_TRANSACTION_FACADE = "REFILL_TRANSACTION_FACADE"
TIPS_TRANSACTION_FACADE = "TIPS_TRANSACTION_FACADE"
